name: Build Driver

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install WDK VS2022 Component
        run: |
          "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vs_installer.exe" modify ^
          --installPath "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise" ^
          --add Microsoft.VisualStudio.Component.WindowsDriverKit ^
          --quiet --norestart --wait

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild tpm-hook/tpm-hook.sln /p:Configuration=Release /p:Platform=x64
